name: Apply Random Video Effects

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'ニコニコ動画のURL'
        required: true
        default: ''
  push:
    paths:
      - 'scripts/**'

# 重要: リポジトリへの書き込み権限を明示的に設定
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # 重要: Personal Access Tokenを使用
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python & FFmpeg
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip
        pip install yt-dlp
      shell: bash

    - name: Get current datetime
      id: datetime
      run: echo "datetime=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Download Niconico video
      run: |
        mkdir -p videos
        yt-dlp -o videos/input_${{ steps.datetime.outputs.datetime }}.mp4 "${{ github.event.inputs.video_link }}"

    - name: Apply random effects
      env:
        VIDEO_IN: videos/input_${{ steps.datetime.outputs.datetime }}.mp4
        VIDEO_OUT: videos/processed_${{ steps.datetime.outputs.datetime }}.mp4
      run: |
        python scripts/apply_effects.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and Push Changes
      run: |
        # 最新の変更を取得
        git pull origin main
        
        # 変更をステージング
        git add videos/processed_${{ steps.datetime.outputs.datetime }}.mp4
        
        # 変更をコミット
        git commit -m "Add processed video $(date +'%Y-%m-%d %H:%M:%S')"
        
        # メインブランチにプッシュ
        git push origin main

    - name: Cleanup input video
      run: |
        rm -f videos/input_${{ steps.datetime.outputs.datetime }}.mp4
