name: Apply Random Video Effects

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'ニコニコ動画のURL'
        required: true
        default: ''
  push:
    paths:
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python & FFmpeg
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip
        pip install yt-dlp
      shell: bash

    - name: Get current datetime
      id: datetime
      run: echo "datetime=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Download Niconico video
      run: |
        mkdir -p videos
        yt-dlp -o videos/input_${{ steps.datetime.outputs.datetime }}.mp4 "${{ github.event.inputs.video_link }}"

    - name: Apply random effects
      env:
        VIDEO_IN: videos/input_${{ steps.datetime.outputs.datetime }}.mp4
        VIDEO_OUT: videos/processed_${{ steps.datetime.outputs.datetime }}.mp4
      run: |
        python scripts/apply_effects.py

    - name: Push to New Branch
      run: |
        # 新しいブランチを作成
        git checkout -b add-video-${{ steps.datetime.outputs.datetime }}
        
        # 生成された動画をブランチに追加
        git add videos/processed_${{ steps.datetime.outputs.datetime }}.mp4
        
        # 変更をコミット
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Add processed video from workflow run"
        
        # ブランチをプッシュ
        git push origin add-video-${{ steps.datetime.outputs.datetime }}

    - name: Cleanup
      run: |
        rm videos/input_${{ steps.datetime.outputs.datetime }}.mp4
