# .github/workflows/apply-effects.yml
name: Apply Random Video Effects

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'ニコニコ動画のURL'
        required: true
        default: ''
  push:
    paths:
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python & FFmpeg
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip
        pip install yt-dlp
      shell: bash

    - name: Download Niconico video
      run: |
        mkdir -p videos
        yt-dlp -o videos/input.mp4 "${{ github.event.inputs.video_link }}"

    - name: Apply random effects
      env:
        VIDEO_IN: videos/input.mp4
        VIDEO_OUT: videos/output.mp4
      run: |
        python scripts/apply_effects.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Processed Video ${{ github.run_number }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload video to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: videos/output.mp4
        asset_name: output.mp4
        asset_content_type: video/mp4
